//src/app/layout.tsx

import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/app/components/SessionProvider';
import Header from '@/app/components/Header/Header';
import Footer from '@/app/components/Footer/Footer';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'MW-Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} grid grid-rows-[auto_1fr_auto] min-h-screen bg-zinc-900 text-zinc-100`}
      >
        <AuthProvider>
          <Header /> {/* ✅ Header is always rendered */}
          <main className="p-4">{children}</main> {/* ✅ Page content */}
          <Footer /> {/* ✅ Footer is always rendered */}
        </AuthProvider>
      </body>
    </html>
  );
}
